// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardAdv: typeof import('./components/card/cardAdv.vue')['default']
    CardFilter: typeof import('./components/card/cardFilter.vue')['default']
    CardListItem: typeof import('./components/card/cardListItem.vue')['default']
    CardMessage: typeof import('./components/card/cardMessage.vue')['default']
    HomeLoading: typeof import('./components/homeLoading.vue')['default']
    IpNav: typeof import('./components/nav/ipNav.vue')['default']
    Loading: typeof import('./components/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillIcon: typeof import('./components/skill/skillIcon.vue')['default']
  }
}
