// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Dialogue: typeof import('./components/dialogue/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HomeLoading: typeof import('./components/homeLoading.vue')['default']
    IpNav: typeof import('./components/nav/ipNav.vue')['default']
    Loading: typeof import('./components/loading.vue')['default']
    SkillGenerate: typeof import('./components/skillGenerate/skillGenerate.vue')['default']
    UnitFilter: typeof import('./components/unit/unitFilter.vue')['default']
    UnitListItem: typeof import('./components/unit/unitListItem.vue')['default']
  }
}

export { }
