export const unitTypeMap = new Map([
  ['サポーター', 'supporter'],
  ['バッファー', 'buffer'],
  ['スコアラー', 'scorer'],
]);

export const unitPropensityMap = new Map([
  ['ボーカル', 'vocal'],
  ['ダンス', 'dance'],
  ['ビジュアル', 'visual'],
]);
// export const unitSkillMap = new Map([
//   ['ボーカル', 'vocal'],
//   ['ダンス', 'dance'],
//   ['ビジュアル', 'visual'],
// ]);
export const skillNormal = [
  'active-skill-score-up',
  'audience-amount-increase',
  'audience-amount-reduction',
  'beat-score-up',
  'combo-continuation',
  'cool-time-reduction',
  'critical-bonus-permil-up',
  'critical-rate-up',
  'dance-down',
  'dance-up',
  'fix-score-get',
  'fix-stamina-recovery',
  'score-get-by-less-fan-amount',
  'score-get-by-less-stamina',
  'score-get-by-more-combo-count',
  'score-get-by-more-fan-amount',
  'score-get-by-more-fan-engage',
  'score-get-by-more-stamina',
  'score-get-by-skill-activation-count',
  'score-get-by-status-effect-type-grade',
  'score-get-by-strength-effect-count',
  'score-get-by-trigger',
  'score-get',
  'score-up',
  'skill-impossible',
  'skill-success-rate-up',
  'special-skill-score-up',
  'stamina-consumption-increase',
  'stamina-consumption-reduction',
  'stamina-recovery',
  'strength-effect-count-increase',
  'strength-effect-value-increase',
  'target-stamina-recovery',
  'tension-up',
  'visual-down',
  'visual-up',
  'vocal-down',
  'vocal-up',
  'weakness-effect-recovery',
];
export const skillYell = [
  'act_character-activity-exp-up',
  'act_fan-event-happening-probability-up',
  'act_fan-event-manager-exp-up',
  'act_promotion-accessory-multi-step-reward-up',
  'act_promotion-gacha-ticket-multi-step-reward-up',
  'act_promotion-gold-up',
  'act_promotion-manager-exp-up',
  'act_refresh-stamina-up',
  'live_accessory-parameter-up',
  'live_active-skill-score-add',
  'live_active-skill-score-multiply',
  'live_audience-amount-up',
  'live_beat-score-add',
  'live_beat-score-multiply',
  'live_card-exp',
  'live_critical-score-multiply',
  'live_dance-add',
  'live_dance-multiply',
  'live_gold',
  'live_manager-exp',
  'live_mental-add',
  'live_mental-multiply',
  'live_passive-skill',
  'live_photo-level-up',
  'live_special-skill-score-add',
  'live_special-skill-score-multiply',
  'live_stamina-add',
  'live_stamina-multiply',
  'live_technique-add',
  'live_technique-multiply',
  'live_visual-add',
  'live_visual-multiply',
  'live_vocal-add',
  'live_vocal-multiply',
];
