export const skill: string[] = [];

export const skillNormal = [
  'active-skill-score-up',
  'audience-amount-increase',
  'audience-amount-reduction',
  'beat-score-up',
  'combo-continuation',
  'combo-score-up',
  'cool-time-reduction',
  'critical-bonus-permil-up',
  'critical-rate-up',
  'dance-down',
  'dance-up',
  'fix-score-get',
  'fix-stamina-recovery',
  'passive-skill-score-up',
  'score-get-by-deck-buffer',
  'score-get-by-deck-supporter',
  'score-get-by-less-fan-amount',
  'score-get-by-less-stamina',
  'score-get-by-more-combo-count',
  'score-get-by-more-fan-amount',
  'score-get-by-more-fan-engage',
  'score-get-by-more-stamina-use',
  'score-get-by-more-stamina',
  'score-get-by-skill-activation-count',
  'score-get-by-status-effect-type-grade',
  'score-get-by-strength-effect-count',
  'score-get-by-trigger',
  'score-get',
  'score-up',
  'skill-impossible',
  'skill-success-rate-up',
  'special-skill-score-up',
  'stamina-consumption',
  'stamina-consumption-increase',
  'stamina-consumption-reduction',
  'stamina-recovery',
  'strength-effect-count-increase',
  'strength-effect-migration-before-active-skill',
  'strength-effect-migration-before-special-skill',
  'strength-effect-value-increase',
  'target-stamina-recovery',
  'tension-up',
  'visual-down',
  'visual-up',
  'vocal-down',
  'vocal-up',
  'weakness-effect-inversion',
  'weakness-effect-prevention',
  'weakness-effect-recovery',
];
export const skillYell = [
  'act_character-activity-exp-up',
  'act_fan-event-happening-probability-up',
  'act_fan-event-manager-exp-up',
  'act_promotion-accessory-multi-step-reward-up',
  'act_promotion-gacha-ticket-multi-step-reward-up',
  'act_promotion-gold-up',
  'act_promotion-manager-exp-up',
  'act_refresh-stamina-up',
  'live_accessory-parameter-up',
  'live_active-skill-score-add',
  'live_active-skill-score-multiply',
  'live_audience-amount-up',
  'live_beat-score-add',
  'live_beat-score-multiply',
  'live_card-exp',
  'live_critical-score-multiply',
  'live_dance-add',
  'live_dance-multiply',
  'live_gold',
  'live_manager-exp',
  'live_mental-add',
  'live_mental-multiply',
  'live_passive-skill',
  'live_photo-level-up',
  'live_special-skill-score-add',
  'live_special-skill-score-multiply',
  'live_stamina-add',
  'live_stamina-multiply',
  'live_technique-add',
  'live_technique-multiply',
  'live_visual-add',
  'live_visual-multiply',
  'live_vocal-add',
  'live_vocal-multiply',
];

export const translateMapCn = new Map([
  ['ボーカル', 'vocal'],
  ['ダンス', 'dance'],
  ['ビジュアル', 'visual'],
  ['スタミナ', 'stamina'],
  ['メンタル', 'mental'],
  ['スコア', 'score-up'],
  ['ビートスコア', 'beat-score'],
  ['Aスキルスコア', 'active-skill-score'],
  ['アピールスコア', 'active-skill-score'],
  ['SPスキルスコア', 'special-skill-score'],
  ['消費スタミナ', 'stamina-consumption'],
  ['スキル成功率', 'skill-success-rate'],
  ['クリティカル', 'live_technique'],
  ['クリティカル率', 'critical-rate'],
  ['クリティカル係数', 'critical-bonus-permil'],
  ['クリティカルスコア', 'live_critical-score-multiply'],
  ['リフレッシュの回復量', 'act_refresh-stamina'],
  ['ファンイベントの獲得マネージャー経験値', 'act_fan-event-manager-exp'],
  ['プロモーションの獲得ゴールド', 'act_promotion-gold'],
  ['プロモーションの獲得コイン', 'act_promotion-gold'],
  ['プロモーションの獲得マネージャー経験値', 'act_promotion-manager-exp'],
  ['プロモーションのアクセサリ獲得率', 'act_promotion-accessory-multi-step-reward'],
  ['回復', 'fix-stamina-recovery'],
  ['スタミナ回復', 'target-stamina-recovery'],
  ['低下効果反転', 'weakness-effect-inversion'],
  ['低下効果防止', 'weakness-effect-prevention'],
  ['低下効果回復', 'weakness-effect-recovery'],
  ['Aスキル前に', 'strength-effect-migration-before-active-skill'],
  ['SPスキル前に', 'strength-effect-migration-before-special-skill'],
  ['テンション', 'tension'],
  ['不調', 'skill-impossible'],
  ['集目', 'audience-amount-increase'],
  ['ステルス', 'audience-amount-reduction'],
  ['強化効果増強', 'strength-effect-value-increase'],
  ['強化効果延長', 'strength-effect-count-increase'],
  ['強化効果', 'strength-effect'],
  ['コンボ継続効果', 'combo-continuation'],
  ['コンボ数', 'combo-count'],
  ['コンボスコア', 'combo-score'],
  ['CT', 'cool-time-reduction'],
  ['観客数割合', 'fan-amount'],
  ['コアファン率', 'fan-engage'],
  ['状態の段階数', 'status-effect-type-grade'],
  ['のスコア獲得', 'score-get'],
  ['が高い', 'status-above'],
  ['が低い', 'status-below'],
  ['上昇効果', 'up'],
  ['低下効果', 'down'],
  ['ビート時', 'beat'],
  ['クリティカル発動時', 'critical'],
  ['発動前', 'before'],
  ['状態の時', 'status'],
  ['コンボ以上時', 'combo'],
  ['自身に', 'oneself'],
]);
